// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC0ZzgvsShNjxVWrD1P7_6il14Z-QRb-U',
    appId: '1:143717055201:web:ff38eef773178c296a55a0',
    messagingSenderId: '143717055201',
    projectId: 'productive-cr',
    authDomain: 'productive-cr.firebaseapp.com',
    storageBucket: 'productive-cr.appspot.com',
    measurementId: 'G-04C1CTTBPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzO_dRr88WLarZzCFoDFPt_xCoD-OCOr4',
    appId: '1:143717055201:android:f458affdf3e01c4a6a55a0',
    messagingSenderId: '143717055201',
    projectId: 'productive-cr',
    storageBucket: 'productive-cr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYO5WkIAMxW4A3-zOTJvWT5sMMrZnNlO8',
    appId: '1:143717055201:ios:89ea7220b52613066a55a0',
    messagingSenderId: '143717055201',
    projectId: 'productive-cr',
    storageBucket: 'productive-cr.appspot.com',
    iosBundleId: 'com.example.productiveCr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYO5WkIAMxW4A3-zOTJvWT5sMMrZnNlO8',
    appId: '1:143717055201:ios:a3e08962630f58f86a55a0',
    messagingSenderId: '143717055201',
    projectId: 'productive-cr',
    storageBucket: 'productive-cr.appspot.com',
    iosBundleId: 'com.example.productiveCr.RunnerTests',
  );
}
